package utils

import (
	"math/big"
	"time"
)

// Log represents a log entry from a transaction.
type Log struct {
	Address     string   // Address that generated the log
	Topics      []string // Topics associated with the log
	Data        []byte   // Data associated with the log
	BlockNumber uint64   // Block number where this log was included
	TxHash      string   // Hash of the transaction this log was part of
	Index       uint     // Index of the log within the block
}

// TransactionDetails represents the details of a blockchain transaction.
type TransactionDetails struct {
	ID          string                 // Transaction ID or hash
	Status      string                 // Status of the transaction (e.g., "pending", "confirmed", "failed")
	BlockNumber uint64                 // Block number where the transaction was included
	Timestamp   time.Time              // Timestamp of the transaction
	From        string                 // Sender address
	To          string                 // Receiver address
	Amount      *big.Int               // Amount transferred
	Fee         *big.Int               // Transaction fee
	Logs        []Log                  // Logs generated by the transaction
	Events      map[string]interface{} // Generic events associated with the transaction
}
