version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.18  # Use the appropriate Go version
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: go mod download

      - run:
          name: Run Tests with Coverage
          command: |
            mkdir -p coverage
            go test -v -coverprofile=coverage/coverage.out ./...
      
      - run:
          name: Display Coverage Report
          command: go tool cover -func=coverage/coverage.out

      - run:
          name: Upload Coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
          when: always

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
