// Code generated by MockGen. DO NOT EDIT.
// Source: ethfactory.go

// Package mock_evm is a generated GoMock package.
package mock_evm

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	evm "github.com/mselser95/blockchain/pkg/evm"
)

// MockClientFactory is a mock of ClientFactory interface.
type MockClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockClientFactoryMockRecorder
}

// MockClientFactoryMockRecorder is the mock recorder for MockClientFactory.
type MockClientFactoryMockRecorder struct {
	mock *MockClientFactory
}

// NewMockClientFactory creates a new mock instance.
func NewMockClientFactory(ctrl *gomock.Controller) *MockClientFactory {
	mock := &MockClientFactory{ctrl: ctrl}
	mock.recorder = &MockClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientFactory) EXPECT() *MockClientFactoryMockRecorder {
	return m.recorder
}

// DialContext mocks base method.
func (m *MockClientFactory) DialContext(ctx context.Context, url string) (evm.ClientInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DialContext", ctx, url)
	ret0, _ := ret[0].(evm.ClientInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DialContext indicates an expected call of DialContext.
func (mr *MockClientFactoryMockRecorder) DialContext(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialContext", reflect.TypeOf((*MockClientFactory)(nil).DialContext), ctx, url)
}
